In [1]:
#Elijah Chanakira & Zeshawn Manzoor

import pandas as pd
import seaborn as sns

salaries = pd.read_excel("levels_comp.xlsx")

salaries = salaries.drop([0,1,2,3])
salaries = salaries.drop(columns=['Other details', 'Tag', 'Unnamed: 14','Unnamed: 15','Unnamed: 16','Unnamed: 17'])

salaries.head(10)

Timestamp    Company   Level  \
4   2017-06-07 11:33:27.260000     Oracle      L3   
5   2017-06-10 17:11:29.485000       eBay    SE 2   
6   2017-06-11 14:53:56.571000     Amazon      L7   
7   2017-06-13 05:35:36.376000       Uber  Senior   
8   2017-06-14 21:22:24.609000  Microsoft      64   
9   2017-06-16 10:44:01.099000     Amazon      L5   
10  2017-06-17 00:23:13.709000      Apple      M1   
11  2017-06-18 23:37:20.592000   Facebook      E4   
12  2017-06-20 10:58:51.061000  Microsoft      60   
13  2017-06-20 18:49:58.669000     Amazon      L5   

                           Title Total Yearly Compensation  \
4                Product Manager                       127   
5              Software Engineer                       100   
6                Product Manager                       310   
7              Software Engineer                       578   
8   Software Engineering Manager                       200   
9              Software Engineer                       173   
10  Software Engineering Manager                       372   
11             Software Engineer                       270   
12             Software Engineer                       157   
13             Software Engineer                       190   

                 Location Years of Experience Years at Company Base Salary  \
4        Redwood City, CA                 1.5              1.5         107   
5       San Francisco, CA                   5                3         NaN   
6             Seattle, WA                   8                0         155   
7                      Sf                  10                2      180000   
8              Redmknd,WA                   9                9      169000   
9   Vancouver, BC, Canada                  11                1      120000   
10              Sunnyvale                   7                5         157   
11         Menlo Park, CA                 3.5                2         160   
12      Mountain View, CA                   5                3         NaN   
13            Seattle, WA                   3                3      110000   

   Stock Grant Value  Bonus Gender  
4                 20     10    NaN  
5                NaN    NaN    NaN  
6                NaN    NaN    NaN  
7            1550000   9000    NaN  
8             100000  30000    NaN  
9                NaN  53000    NaN  
10               180     35    NaN  
11               NaN    NaN    NaN  
12               NaN    NaN    NaN  
13             80000    NaN    NaN

# 1. Introduction

# 3. Data Cleansing
All of this data is self reported so some of the data was misreported or contains human error. Unfortunately, the form that was used to collect the data did not utilize any input validation which resulted in several inconsistencies. We made sure: to replace and remove null values, parse common spelling mistakes, and other data cleansing techniques.

## a. Missing Values
First we decided to fill in any missing values so that we could later fix them or remove them. Values that went unreported including the base salary, stocks, bonus, years of experience, and years at the company were all given a value of 0. We chose to do this because we planned on using a lot of these values in our later analysis and we could either replce them with close to accurate values or remove them from the data set entirely.

In [2]:
# Fill in Missing Values
salaries['Base Salary'].fillna(0, inplace=True)
salaries['Stock Grant Value'].fillna(0, inplace=True)
salaries['Bonus'].fillna(0, inplace=True)
salaries['Years of Experience'].fillna(0, inplace=True)
salaries['Years at Company'].fillna(0, inplace=True)

salaries.head(5)

Timestamp    Company   Level  \
4  2017-06-07 11:33:27.260000     Oracle      L3   
5  2017-06-10 17:11:29.485000       eBay    SE 2   
6  2017-06-11 14:53:56.571000     Amazon      L7   
7  2017-06-13 05:35:36.376000       Uber  Senior   
8  2017-06-14 21:22:24.609000  Microsoft      64   

                          Title Total Yearly Compensation           Location  \
4               Product Manager                       127   Redwood City, CA   
5             Software Engineer                       100  San Francisco, CA   
6               Product Manager                       310        Seattle, WA   
7             Software Engineer                       578                 Sf   
8  Software Engineering Manager                       200         Redmknd,WA   

  Years of Experience  Years at Company  Base Salary  Stock Grant Value  \
4                 1.5               1.5        107.0               20.0   
5                   5               3.0          0.0                0.0   
6                   8               0.0        155.0                0.0   
7                  10               2.0     180000.0          1550000.0   
8                   9               9.0     169000.0           100000.0   

     Bonus Gender  
4     10.0    NaN  
5      0.0    NaN  
6      0.0    NaN  
7   9000.0    NaN  
8  30000.0    NaN

Next we did a lot of work on string values. First we waanted to remove inconsistency of cases, so we changed all string values to lowercase. From there we removed any leading and trailing spaces.  

In [3]:
# Fix String Cases, so that I can do analysis by company
salaries['Company'] = salaries['Company'].str.lower()
salaries['Company'] = salaries['Company'].str.strip()

salaries['Location'] = salaries['Location'].str.lower()
salaries['Location'] = salaries['Location'].str.strip()

salaries['Level'] = salaries['Location'].str.lower()
salaries['Level'] = salaries['Location'].str.strip()

salaries['Title'] = salaries['Title'].str.lower()
salaries['Title'] = salaries['Title'].str.strip()

salaries.head(5)

Timestamp    Company              Level  \
4  2017-06-07 11:33:27.260000     oracle   redwood city, ca   
5  2017-06-10 17:11:29.485000       ebay  san francisco, ca   
6  2017-06-11 14:53:56.571000     amazon        seattle, wa   
7  2017-06-13 05:35:36.376000       uber                 sf   
8  2017-06-14 21:22:24.609000  microsoft         redmknd,wa   

                          Title Total Yearly Compensation           Location  \
4               product manager                       127   redwood city, ca   
5             software engineer                       100  san francisco, ca   
6               product manager                       310        seattle, wa   
7             software engineer                       578                 sf   
8  software engineering manager                       200         redmknd,wa   

  Years of Experience  Years at Company  Base Salary  Stock Grant Value  \
4                 1.5               1.5        107.0               20.0   
5                   5               3.0          0.0                0.0   
6                   8               0.0        155.0                0.0   
7                  10               2.0     180000.0          1550000.0   
8                   9               9.0     169000.0           100000.0   

     Bonus Gender  
4     10.0    NaN  
5      0.0    NaN  
6      0.0    NaN  
7   9000.0    NaN  
8  30000.0    NaN

Finally, when analyzing the data we found many variations of common locations. For example some locations were represented as 'San Francisco,CA', 'San Francisco , CA' etc. The commas and spaces varied with many of the locations, so the final major decision we made was to remove spaces within strings. Affterwards we removed the commas and replaced them with spaces. Although that concatenated any locations with more than 3 words, it did a good job of making sure several locations were uniform.

In [4]:
#Remove all spaces and then turn commas into space
salaries['Location'] = salaries['Location'].str.replace(' ','')
salaries['Location'] = salaries['Location'].str.replace(',',' ')

salaries.head(5)

Timestamp    Company              Level  \
4  2017-06-07 11:33:27.260000     oracle   redwood city, ca   
5  2017-06-10 17:11:29.485000       ebay  san francisco, ca   
6  2017-06-11 14:53:56.571000     amazon        seattle, wa   
7  2017-06-13 05:35:36.376000       uber                 sf   
8  2017-06-14 21:22:24.609000  microsoft         redmknd,wa   

                          Title Total Yearly Compensation         Location  \
4               product manager                       127   redwoodcity ca   
5             software engineer                       100  sanfrancisco ca   
6               product manager                       310       seattle wa   
7             software engineer                       578               sf   
8  software engineering manager                       200       redmknd wa   

  Years of Experience  Years at Company  Base Salary  Stock Grant Value  \
4                 1.5               1.5        107.0               20.0   
5                   5               3.0          0.0                0.0   
6                   8               0.0        155.0                0.0   
7                  10               2.0     180000.0          1550000.0   
8                   9               9.0     169000.0           100000.0   

     Bonus Gender  
4     10.0    NaN  
5      0.0    NaN  
6      0.0    NaN  
7   9000.0    NaN  
8  30000.0    NaN

Another problem that we encountered was that some locations had several different representations. For example San Francisco could be represensted as 'SF', 'San Fran', 'SFO', etc. So although we cleaned a large amount of locations, more work could be done to address these abbreviations. The immediate options we considered were using a library or manually fixing each string.

Originally, we had planned on individually removing companies whose names were mispelled but a less time consuming process was to remove any companies who had 4 or less entries in the data set. This way we could adjust the threshold as we saw fit. This does not require knowledge of all reported companies, and ultimately reduces potential human error. 

We could have potentially applied this technique to mispelled locations, but that could have greatly effected other aspects of the data.

In [5]:
counts= salaries['Company'].value_counts()

#Condition for companies we would like to ignore
to_ignore = counts[counts < 5].index

cleansed = pd.DataFrame(columns=salaries.columns)

for index,row in salaries.iterrows():
    if(row['Company'] not in to_ignore):
        cleansed = cleansed.append(row, ignore_index=True)
    
print(cleansed['Company'].unique())

['oracle' 'ebay' 'amazon' 'uber' 'microsoft' 'apple' 'facebook'
 'salesforce' 'vmware' 'oath' 'google' 'amazon.com' 'netflix' 'expedia'
 'zillow' 'pinterest' 'linkedin' 'intuit' 'yahoo' 'adobe' 'symantec' 'dell'
 'intel' 'lyft' 'snap' 'yelp' 'airbnb' nan 'nvidia' 'sap' 'credit karma'
 'walmart labs' 'dropbox' 'twitter' 'tableau software' 'cisco' 'splunk'
 'ibm' 'walmartlabs' 'spotify' 'capital one' 'qualcomm' 'workday' 'tesla'
 'paypal' 'box' 'visa' 'ge digital' 'ca technologies' 'goldman sachs'
 'square' 'akamai' 'godaddy' 'bloomberg' 'yandex' 'accenture' 'zendesk'
 'booking.com' 'autodesk' 't-mobile' 'hulu' 'qualtrics' 'atlassian'
 'groupon' 'cloudera' 'indeed' 'deloitte' 'mic' 'mi' 'jpmorgan chase'
 'test' 'comcast' 'american express']


In [6]:
cleansed.loc[cleansed['Base Salary'] > 500000]

Timestamp    Company               Level  \
204  2018-01-05 13:59:58.342  microsoft         redmond, wa   
305  2018-02-19 19:14:28.545      intel       hillsboro, or   
636  2018-05-21 16:34:37.314     google       mountain view   
772  2018-06-09 14:28:37.737    netflix       los gatos, ca   
905  2018-06-29 17:36:14.483       lyft  sand francisco, ca   
1059 2018-07-25 08:30:21.814     amazon        tokyo, japan   
1854 2018-09-20 22:40:58.175    netflix       los gatos, ca   

                             Title Total Yearly Compensation  \
204                product manager                       250   
305              software engineer                       300   
636              software engineer                       800   
772   software engineering manager                       525   
905              software engineer                       300   
1059             software engineer                       810   
1854             software engineer                       630   

              Location Years of Experience  Years at Company  Base Salary  \
204         redmond wa                  13              13.0    1659870.0   
305       hillsboro or                  22              20.0    2000000.0   
636       mountainview                   2               2.0     650000.0   
772        losgatos ca                  14               1.0     525000.0   
905   sandfrancisco ca                   4               0.0    1750000.0   
1059       tokyo japan                   0               1.0    6500000.0   
1854       losgatos ca                  10               1.0     600000.0   

      Stock Grant Value     Bonus Gender  
204             49850.0   31500.0    NaN  
305             45000.0   55000.0    NaN  
636            150000.0  160000.0   Male  
772                 0.0       0.0   Male  
905            400000.0   20000.0   Male  
1059          1000000.0       0.0   Male  
1854               30.0       0.0    NaN

Next we decided to do a deeper dive into many of the values stored in yearly compensation and base salary. The data above shows another problem with user reported data. The entry at index 204, 305, and 905 are good examples of users adding an extra zero in their base salary which ultimately inflates the base salary column. It is clear that the value was inflated because the total compensation is not only significantly lower that the base salary, it is also off by a zero. So what we decided to do next was to remove any utlier values and cleansing any base salaries that are misreported. 

Another example index 1059, the user reported a base salary of 6,500,000 Dollars and a total compensation of $810,000. Normally we would have removed the extra zero; however, this data set is a cause for concern because SDE I is an amazon new grad, so it is hard to determine the total accuracy of this data set. Finally we chose to keep the netflix salaries because the years of experience remove potential concerns.

In [7]:
#OOOutlier values
cleansed = cleansed.drop(cleansed.index[[1059]])
cleansed = cleansed.drop(cleansed.index[[636]])

cleansed.loc[cleansed.index == 204, 'Base Salary'] = 165987
cleansed.loc[cleansed.index == 305, 'Base Salary'] = 200000
cleansed.loc[cleansed.index == 905, 'Base Salary'] = 175000

salaries  = cleansed

cleansed.loc[cleansed['Base Salary'] > 500000]

Timestamp  Company          Level  \
772  2018-06-09 14:28:37.737  netflix  los gatos, ca   
1854 2018-09-20 22:40:58.175  netflix  los gatos, ca   

                             Title Total Yearly Compensation     Location  \
772   software engineering manager                       525  losgatos ca   
1854             software engineer                       630  losgatos ca   

     Years of Experience  Years at Company  Base Salary  Stock Grant Value  \
772                   14               1.0     525000.0                0.0   
1854                  10               1.0     600000.0               30.0   

      Bonus Gender  
772     0.0   Male  
1854    0.0    NaN

In [8]:
condition = cleansed['Base Salary'] < 1000
cleansed.loc[condition]

Timestamp     Company                        Level  \
0    2017-06-07 11:33:27.260      oracle             redwood city, ca   
1    2017-06-10 17:11:29.485        ebay            san francisco, ca   
2    2017-06-11 14:53:56.571      amazon                  seattle, wa   
6    2017-06-17 00:23:13.709       apple                    sunnyvale   
7    2017-06-18 23:37:20.592    facebook               menlo park, ca   
8    2017-06-20 10:58:51.061   microsoft            mountain view, ca   
10   2017-06-21 17:27:47.153   microsoft                  seattle, wa   
11   2017-06-22 12:37:51.385   microsoft                      redmond   
12   2017-06-22 13:55:26.154   microsoft                  seattle, wa   
13   2017-06-22 21:39:47.595        uber                san francisco   
14   2017-06-22 23:08:15.525   microsoft                      redmond   
15   2017-06-26 21:25:44.837   microsoft                  seattle, wa   
17   2017-06-30 16:29:50.420  salesforce                san francisco   
18   2017-07-02 14:16:51.490   microsoft                bellevue,  wa   
19   2017-07-03 19:28:08.795   microsoft                      redmond   
20   2017-07-07 22:29:33.824   microsoft                  seattle, wa   
22   2017-07-14 21:36:15.035      amazon                      seattle   
23   2017-07-16 00:03:56.332      vmware  bangaluru, karnataka, india   
24   2017-07-16 16:50:46.016      amazon                  seattle, wa   
25   2017-07-17 21:50:51.816    facebook            san francisco, ca   
26   2017-07-20 22:35:48.794    facebook               menlo park, ca   
28   2017-07-22 22:20:17.299        uber                san francisco   
29   2017-07-24 12:21:07.422       apple                   uk, london   
30   2017-07-24 23:14:39.033   microsoft                  redmond, wa   
32   2017-07-25 14:44:52.850        oath                     bay area   
35   2017-07-29 19:56:08.337   microsoft                 bellevue, wa   
36   2017-07-31 15:54:17.176  amazon.com                      seattle   
37   2017-07-31 15:55:01.355  amazon.com                      seattle   
39   2017-08-01 13:46:54.026   microsoft                  seattle, wa   
41   2017-08-04 11:04:03.188   microsoft                  redmond, wa   
...                      ...         ...                          ...   
3616 2018-12-06 06:54:04.556   microsoft                  redmond, wa   
3617 2018-12-06 10:19:38.825        dell                hopkinton, ma   
3618 2018-12-06 10:37:13.490     twitter            san francisco, ca   
3619 2018-12-06 12:06:20.032      google                  seattle, wa   
3620 2018-12-06 13:31:43.129       apple                    cupertino   
3621 2018-12-06 13:53:03.526     workday                san francisco   
3622 2018-12-06 18:48:47.142      amazon                  seattle, wa   
3623 2018-12-06 20:49:09.637      google                     kirkland   
3624 2018-12-06 20:56:42.967      google                sunnyvale, ca   
3625 2018-12-06 21:45:14.668      google            san francisco, ca   
3626 2018-12-06 22:11:03.453       cisco                       rtp,nc   
3627 2018-12-06 22:48:37.473    linkedin                sunnyvale, ca   
3628 2018-12-06 22:48:39.330        ebay                 san jose, ca   
3629 2018-12-06 22:51:10.395   microsoft                  redmond, wa   
3630 2018-12-06 22:52:59.583      amazon                  seattle, wa   
3631 2018-12-06 23:10:02.241      oracle                      oakland   
3632 2018-12-06 23:26:28.300  salesforce            san francisco, ca   
3633 2018-12-06 23:43:59.455    deloitte   amsterdam, nh, netherlands   
3634 2018-12-07 01:48:02.621   microsoft            san francisco, ca   
3635 2018-12-07 12:58:30.770     groupon                      seattle   
3636 2018-12-07 15:12:14.397      square                      atlanta   
3637 2018-12-07 16:00:58.125      google                 new york, ny   
3638 2018-12-07 17:22:19.548  salesforce            san francisco, ca   
3639

Next, we adjusted any base salaries that are less than 1000 because the individuals who completed the form did not adjust it it to the closest hundred thousandth. For values whos title and salary did not match, I manually cross-checked their years of experience with posts on [H1bdata.info](h1bdata.info) , because those entries are self-reported but are required by law to be accurate.

In [9]:
un_cleansed = cleansed[condition]

cleansed.loc[condition, 'Base Salary'] = un_cleansed['Base Salary'] * 100
salaries = cleansed

Finally we drop any values that are equal to zero because we have no other factors to use in order to calculate their salaries.

We also did a quick check to make sure that any total yearly compensations that were greater than or equal to $1,000,000 made sense. Meaning entries had multiple years of experience, and the sum of their base salary & stocks were near that value.

In [10]:
salaries = salaries.drop(salaries[salaries['Base Salary'] == 0].index)
salaries.loc[salaries['Total Yearly Compensation'] >= 1000]

Timestamp    Company               Level  \
232  2018-01-24 04:51:35.473     google        new york, ny   
238  2018-01-27 07:29:29.677       uber       san francisco   
446  2018-04-11 23:06:10.708   linkedin  mountain view , ca   
578  2018-05-13 23:54:26.227       snap                  sf   
715  2018-06-03 19:11:21.447     google    mountain view ca   
1069 2018-07-26 19:44:28.571  microsoft         seattle, wa   

                             Title Total Yearly Compensation         Location  \
232              software engineer                      1120       newyork ny   
238              software engineer                      1500     sanfrancisco   
446   software engineering manager                      1000  mountainview ca   
578              software engineer                      1400               sf   
715                product manager                      1850   mountainviewca   
1069               product manager                      1240       seattle wa   

     Years of Experience  Years at Company  Base Salary  Stock Grant Value  \
232                   10               7.0      25200.0              790.0   
238                   15               3.0      30000.0             5000.0   
446                   17               3.0     275000.0           700000.0   
578                   11               2.0      25000.0             1150.0   
715                   13               7.0      30000.0             1450.0   
1069                  25               9.0     310000.0           550000.0   

         Bonus Gender  
232       78.0    NaN  
238       50.0    NaN  
446    20000.0    NaN  
578        0.0   Male  
715      100.0   Male  
1069  180000.0   Male

Talk about level, years of experience, and total comp

# Data Analysis
- Salary based on location, years of experience, company
- Percent difference between ranks
- Possibly set premade ranks based on years of experience
- Analyze salary by gender

In [11]:
# Average salary based on location
locFrame = (salaries.groupby(['Location', 'Base Salary'], as_index=False).mean().groupby('Location')['Base Salary'].mean().round().reset_index())
locFrame = locFrame.sort_values('Base Salary', ascending = False)
locFrame.head()

# The highest recorded average base salary comes from Tokyo, Japan, with a average base salary of almost twice the size of its runner up, San Fransisco. This data does not take into account the mispelled locations that skew the average base salary. 

Location  Base Salary
98         losgatos     380000.0
228             sfo     230000.0
250    unitedstates     220000.0
176         redwood     210000.0
206  sanjose ca usa     190000.0

In [ ]:
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import numpy as np

# Average salary based on years of experience
yoeFrame = (salaries.groupby(['Years of Experience', 'Base Salary'], as_index=False).mean().groupby('Years of Experience')['Base Salary'].mean().round().reset_index())
yoeFrame = yoeFrame.sort_values('Base Salary', ascending = False)
plt.scatter(salaries['Years of Experience'],salaries['Base Salary'])
plt.ylim(0,800000)
plt.show()

# The data projects that the highest average base salary comes from people with 22 years of experience for a salary of ~$285k. Meanwhile, workers with only 2 years of experience were projected to recieve ~$130k as a base salary, which is almost half the salary of someone with 22 years of experience. 
# The scatter plot created shows an upward trend. As years of experience increases, we can see that average base salary does as well.

In [ ]:
# Average Salary based on company
companyFrame = (salaries.groupby(['Company', 'Base Salary'], as_index=False).mean().groupby('Company')['Base Salary'].mean().round().reset_index())
companyFrame = companyFrame.sort_values('Base Salary', ascending = False)
companyFrame.head()

# Squarespace has by far the largest average base salary of ~600k per year. Followed up is ey with only half that amount. Interestingly, the 5th highest average base salary from oracle oci is three times smaller than that of squarespace. 

In [ ]:
# Analyze Salary by Gender
genderFrame = (salaries.groupby(['Gender', 'Base Salary'], as_index=False).mean().groupby('Gender')['Base Salary'].mean().round().reset_index())
genderFrame
# According to the data: On average, men's base salaries were almost twice as much as women's base salaries. However, The unspecified gender category could either skew the average base salary towards women or towards men.

In [ ]:
rankFrame = (salaries.groupby(['Level','Years of Experience'])[['Base Salary']]).mean()
rankFrame

# Future and Conclusion 
Unfortunately this data set was extremely uncleanly, so a lot of data had to be replaced and removed
If I had more time I would have cleaned the location
